vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        imageProfile:
            uri_prefix: http://127.0.0.1:8000
            upload_destination: '%kernel.project_dir%/public/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: App\Namer\ImageDirectoryNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true