controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
lieux_par_ville:
    path: '/lieux/par-ville/{villeId}'
    controller: 'App\Controller\LieuxController::lieuxParVille'
